INSERT INTO `blog`.`etiquetas` (`id`,`nombre_etiqueta`) VALUES (1,'Robótica');
INSERT INTO `blog`.`etiquetas` (`id`,`nombre_etiqueta`) VALUES (2,'Computación');
INSERT INTO `blog`.`etiquetas` (`id`,`nombre_etiqueta`) VALUES (3,'Teléfonos Móviles');
INSERT INTO `blog`.`etiquetas` (`id`,`nombre_etiqueta`) VALUES (4,'Automovilismo');
INSERT INTO `blog`.`etiquetas` (`id`,`nombre_etiqueta`) VALUES (5,'Campeonatos');
INSERT INTO `blog`.`etiquetas` (`id`,`nombre_etiqueta`) VALUES (6,'Equipos');
INSERT INTO `blog`.`etiquetas` (`id`,`nombre_etiqueta`) VALUES (7,'Bolsa de valores');
INSERT INTO `blog`.`etiquetas` (`id`,`nombre_etiqueta`) VALUES (8,'Inversiones');
INSERT INTO `blog`.`etiquetas` (`id`,`nombre_etiqueta`) VALUES (9,'Brokers');
INSERT INTO `blog`.`etiquetas` (`id`,`nombre_etiqueta`) VALUES (10,'Celebridades');
INSERT INTO `blog`.`etiquetas` (`id`,`nombre_etiqueta`) VALUES (11,'Eventos');
INSERT INTO `blog`.`etiquetas` (`id`,`nombre_etiqueta`) VALUES (12,'Moda');
INSERT INTO `blog`.`etiquetas` (`id`,`nombre_etiqueta`) VALUES (13,'Avances');
INSERT INTO `blog`.`etiquetas` (`id`,`nombre_etiqueta`) VALUES (14,'Nobel');
INSERT INTO `blog`.`etiquetas` (`id`,`nombre_etiqueta`) VALUES (15,'Matemáticas');
INSERT INTO `blog`.`etiquetas` (`id`,`nombre_etiqueta`) VALUES (16,'Química');
INSERT INTO `blog`.`etiquetas` (`id`,`nombre_etiqueta`) VALUES (17,'Física');
INSERT INTO `blog`.`etiquetas` (`id`,`nombre_etiqueta`) VALUES (18,'Largo plazo');
INSERT INTO `blog`.`etiquetas` (`id`,`nombre_etiqueta`) VALUES (19,'Bienes Raíces');
INSERT INTO `blog`.`etiquetas` (`id`,`nombre_etiqueta`) VALUES (20,'Estilo');